const jlptN5Set = [
  { prompt: "水", answer: "water" },
  { prompt: "火", answer: "fire" },
  { prompt: "木", answer: "tree" },
  { prompt: "金", answer: "gold / money" },
  { prompt: "土", answer: "earth / soil" },
  { prompt: "山", answer: "mountain" },
  { prompt: "川", answer: "river" },
  { prompt: "空", answer: "sky" },
  { prompt: "雨", answer: "rain" },
  { prompt: "石", answer: "stone" },
  { prompt: "犬", answer: "dog" },
  { prompt: "猫", answer: "cat" },
  { prompt: "人", answer: "person" },
  { prompt: "子", answer: "child" },
  { prompt: "先生", answer: "teacher" },
  { prompt: "学生", answer: "student" },
  { prompt: "学校", answer: "school" },
  { prompt: "本", answer: "book" },
  { prompt: "車", answer: "car" },
  { prompt: "電車", answer: "train" },
  { prompt: "駅", answer: "station" },
  { prompt: "家", answer: "house" },
  { prompt: "朝", answer: "morning" },
  { prompt: "夜", answer: "night" },
  { prompt: "今日", answer: "today" },
  { prompt: "明日", answer: "tomorrow" },
  { prompt: "食べる", answer: "to eat" },
  { prompt: "飲む", answer: "to drink" },
  { prompt: "行く", answer: "to go" },
  { prompt: "見る", answer: "to see / watch" },
];

export default jlptN5Set;
